// export default catchAsync = (fn:Function) => {
//     return (req:Request, res:Response, next: NextFunction) => {
//         try{
//            fn()
//         }catch(err){

//         }
//     }
// }
